version: "3"

services:
  thowebsite:
    build:
      context: ./
      dockerfile: Dockerfile-preview
    stdin_open: true
    tty: true
    container_name: tho_website
    restart: always
    ports:
      - "3000:3000"
